server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /env.js {
        return 200 'window.__ENV__ = { VITE_API_URL: "$VITE_API_URL" };';
        add_header Content-Type application/javascript;
    }
}